-- ═══════════════════════════════════════════════════════════════════════
--  LoveLab × IGI — bring the database from 2026-08-27 to 2026-09-15
-- ═══════════════════════════════════════════════════════════════════════
--
--  Generated by scripts/build-igi-update.mjs from lib/igi/seed.json — do not edit by hand.
--  Adds what the new sheet has, corrects what it changed, leaves the rest.
--  Safe to run twice. Nothing recorded by the app itself is touched.

BEGIN;

-- Quantities ordered that moved in IGI's file
UPDATE public.igi_models SET qty_ordered = 700, updated_at = now() WHERE serial = 'LGAJ6576';  -- Cuty Fancy Color: 833 → 700
UPDATE public.igi_models SET qty_ordered = 700, updated_at = now() WHERE serial = 'LGAJ6577';  -- Cuty Fancy Color: 833 → 700
UPDATE public.igi_models SET qty_ordered = 700, updated_at = now() WHERE serial = 'LGAJ6578';  -- Cuty Fancy Color: 833 → 700
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6588';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6588' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6589';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6589' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6590';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6590' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6591';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6591' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6592';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6592' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6593';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6593' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6594';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6594' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6595';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6595' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6596';  -- —: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6596' AND state = 'reserved';  -- —: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6597';  -- A: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6597' AND state = 'reserved';  -- A: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6598';  -- B: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6598' AND state = 'reserved';  -- B: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6599';  -- C: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6599' AND state = 'reserved';  -- C: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6600';  -- D: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6600' AND state = 'reserved';  -- D: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6601';  -- E: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6601' AND state = 'reserved';  -- E: reserved → in_use
UPDATE public.igi_models SET qty_ordered = 500, updated_at = now() WHERE serial = 'LGAJ6602';  -- F: none → 500
UPDATE public.igi_models SET state = 'in_use', updated_at = now() WHERE serial = 'LGAJ6602' AND state = 'reserved';  -- F: reserved → in_use

-- Opening runs whose size changed
UPDATE public.igi_batches SET qty = 700 WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6576') AND reference = 'initial order';  -- LGAJ6576: 833 → 700
UPDATE public.igi_batches SET qty = 700 WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6577') AND reference = 'initial order';  -- LGAJ6577: 833 → 700
UPDATE public.igi_batches SET qty = 700 WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6578') AND reference = 'initial order';  -- LGAJ6578: 833 → 700
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6588'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6588') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6589'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6589') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6590'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6590') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6591'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6591') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6592'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6592') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6593'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6593') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6594'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6594') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6595'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6595') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6596'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6596') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6597'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6597') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6598'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6598') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6599'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6599') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6600'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6600') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6601'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6601') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
  SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6602'), 500, '2026-09-15', 'initial order'
  WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6602') AND reference = 'initial order');

-- Movements: new days, and corrected figures on days already recorded
UPDATE public.igi_visit_lines SET qty_requested = 14, qty_issued = 14, qty_received = 14
  WHERE visit_id = (SELECT id FROM public.igi_visits WHERE visit_no = 22) AND model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535');  -- V-022 2026-08-26 LGAJ6535: 7 → 14
-- V-024 2026-09-07: 1 line(s), 140 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (24, '2026-09-07', 'closed', false, NULL, '2026-09-07T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 24), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 140, 140, 140)
  ON CONFLICT (visit_id, model_id) DO NOTHING;

-- V-025 2026-09-08: 1 line(s), 140 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (25, '2026-09-08', 'closed', false, NULL, '2026-09-08T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 25), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 140, 140, 140)
  ON CONFLICT (visit_id, model_id) DO NOTHING;

-- V-026 2026-09-08: 9 line(s), 123 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (26, '2026-09-08', 'closed', false, NULL, '2026-09-08T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 55, 55, 55)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 20, 20, 20)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 14, 14, 14)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 5, 5, 5)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 5, 5, 5)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 2, 2, 2)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 6, 6, 6)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 26), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;

-- V-027 2026-09-09: 28 line(s), 577 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (27, '2026-09-09', 'closed', false, NULL, '2026-09-09T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 124, 124, 124)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 38, 38, 38)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 14, 14, 14)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 140, 140, 140)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 5, 5, 5)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 2, 2, 2)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6541'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 23, 23, 23)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 5, 5, 5)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 81, 81, 81)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 24, 24, 24)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6557'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 24, 24, 24)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 9, 9, 9)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563'), 5, 5, 5)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6566'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6567'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6568'), 17, 17, 17)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6569'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6571'), 8, 8, 8)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6572'), 3, 3, 3)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6573'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 27), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6574'), 2, 2, 2)
  ON CONFLICT (visit_id, model_id) DO NOTHING;

-- V-028 2026-09-10: 9 line(s), 93 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (28, '2026-09-10', 'closed', false, NULL, '2026-09-10T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 28, 28, 28)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 39, 39, 39)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 16, 16, 16)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 3, 3, 3)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 3, 3, 3)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6553'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 28), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;

-- V-029 2026-09-15: 15 line(s), 263 certificates
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
  VALUES (29, '2026-09-15', 'closed', false, NULL, '2026-09-15T12:00:00Z')
  ON CONFLICT (visit_no) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 30, 30, 30)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 57, 57, 57)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 22, 22, 22)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 36, 36, 36)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 21, 21, 21)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 8, 8, 8)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 6, 6, 6)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 2, 2, 2)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 18, 18, 18)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6566'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6567'), 15, 15, 15)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6568'), 17, 17, 17)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6571'), 12, 12, 12)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6572'), 3, 3, 3)
  ON CONFLICT (visit_id, model_id) DO NOTHING;
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
  VALUES ((SELECT id FROM public.igi_visits WHERE visit_no = 29), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6573'), 1, 1, 1)
  ON CONFLICT (visit_id, model_id) DO NOTHING;


-- ── The figures must land where the seed says. Only imported movements
-- ── (created_by IS NULL) are counted: the app's own are not the sheet's.
DO $$
DECLARE
  ordered bigint; attributed bigint; unattributed bigint; movements bigint;
BEGIN
  SELECT coalesce(sum(qty),0) INTO ordered FROM public.igi_batches WHERE reference = 'initial order';
  SELECT coalesce(sum(l.qty_issued),0) INTO attributed FROM public.igi_visit_lines l JOIN public.igi_visits v ON v.id = l.visit_id WHERE v.created_by IS NULL;
  SELECT coalesce(sum(unattributed_total),0) INTO unattributed FROM public.igi_visits WHERE created_by IS NULL;
  SELECT count(*) INTO movements FROM public.igi_visits WHERE created_by IS NULL;
  IF ordered <> 70100 THEN RAISE EXCEPTION 'certificates ordered: % (expected 70100)', ordered; END IF;
  IF attributed <> 5121 THEN RAISE EXCEPTION 'issued with a model: % (expected 5121)', attributed; END IF;
  IF unattributed <> 3245 THEN RAISE EXCEPTION 'issued with no model: % (expected 3245)', unattributed; END IF;
  IF movements <> 29 THEN RAISE EXCEPTION 'movements from IGI''s file: % (expected 29)', movements; END IF;
  RAISE NOTICE 'IGI figures as of 2026-09-15: ordered %, issued with a model %, without %, movements % — all as expected', ordered, attributed, unattributed, movements;
END $$;

COMMIT;
