-- ═══════════════════════════════════════════════════════════════════════
--  LoveLab × IGI — switch the certificate module on
-- ═══════════════════════════════════════════════════════════════════════
--
--  Paste this whole file into the Supabase SQL editor and run it.
--
--  It does three things:
--    1. creates the tables the certificate screens read from, and sets out
--       exactly what IGI may and may not do once they have a login
--    2. loads the opening balances from IGI's file, 27 August 2026
--    3. checks every figure and STOPS if any of them is wrong
--
--  A successful run ends with:  IGI: ALL FIGURES MATCH
--  Anything else means nothing was saved — the whole run is one transaction.
--
--  Running it twice is safe. It corrects rather than duplicates.
--
--  Generated by scripts/build-igi-switch-on.mjs — do not edit by hand.

BEGIN;

-- ─── 1 of 3 · The tables ───────────────────────────────────────────────

-- LoveLab x IGI — shared certificate stock and history.
--
-- Every LoveLab piece ships with an IGI certificate. Today the flow is tracked in two
-- Excel files that never talk to each other. These tables hold the movements once and
-- everything else is derived from them (see lib/igi/derive.js).
--
-- The certificate SERIAL is the identity, never the name. Names can change on any day
-- without breaking history. One name is shared by both companies.
--
-- Visibility is deliberately asymmetric: LoveLab sees both sides, IGI sees only their
-- own stock and the requests addressed to them. IGI must never see how fast LoveLab's
-- shelf empties, because that is LoveLab's sales rate.

-- ─── 1. IGI role flag ───────────────────────────────────────────────────────
-- Mirrors the commercial-assistant flag (20260818090000). A flag rather than a new
-- `role` value, because profiles_role_check only allows 'admin' | 'member'.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_igi boolean DEFAULT false;

COMMENT ON COLUMN public.profiles.is_igi IS
  'IGI Antwerp staff: sees only the IGI portal — their own stock, the requests sent to them, their batches and invoices. Never LoveLab''s shelf.';

CREATE OR REPLACE FUNCTION public.is_igi()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND is_igi = true
  )
$$;

GRANT EXECUTE ON FUNCTION public.is_igi() TO authenticated;

-- ─── 2. igi_models ──────────────────────────────────────────────────────────
-- 61 in use, 15 reserved serials, 3 waiting for a serial.

CREATE TABLE IF NOT EXISTS public.igi_models (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- 'LGAJ6529' = LG (lab grown) + AJ (IGI series) + 4 model digits.
  -- Null only while IGI has not numbered the model yet.
  serial        text,
  -- 'LGAJ65292505' — the same serial carrying the YYMM production month.
  serial_full   text,
  -- LoveLab decides the name, IGI follows it. Where one certificate serves several
  -- products the names are merged into this one label, so the stock is counted once.
  name          text        NOT NULL,
  -- What IGI's file called it at import time. Kept for the trail, never displayed.
  igi_name      text,
  -- Text, not integer: '6+1' and '3+2' are real values in the source file.
  stones        text,
  carat         numeric(4,2),
  shape         text,
  spec          text,
  -- in_use          — has a serial and a quantity
  -- reserved        — IGI assigned the serial, nothing was ever ordered. Kept on record
  --                   so the numbers are not lost; hidden from operational screens.
  --                   (These carried "v" instead of a quantity in the source file,
  --                   which is what produced 15 #VALUE! errors.)
  -- awaiting_serial — asked for, IGI has not numbered it. Cannot be requested.
  state         text        NOT NULL DEFAULT 'in_use'
                            CHECK (state IN ('in_use', 'reserved', 'awaiting_serial')),
  qty_ordered   integer     CHECK (qty_ordered IS NULL OR qty_ordered >= 0),
  -- Alert levels. One owner each: LoveLab owns shelf_min, IGI owns pool_min.
  -- Plain numbers only — no "weeks of cover", that was tried and removed.
  shelf_min     integer     NOT NULL DEFAULT 25 CHECK (shelf_min >= 0),
  pool_min      integer     CHECK (pool_min IS NULL OR pool_min >= 0),
  sort_order    integer,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  -- A model waiting for a serial has none yet, so this cannot be a plain UNIQUE.
  CONSTRAINT igi_models_serial_required_when_numbered
    CHECK (state = 'awaiting_serial' OR serial IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS igi_models_serial_key
  ON public.igi_models (serial) WHERE serial IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_igi_models_state
  ON public.igi_models (state);

-- ─── 3. igi_batches ─────────────────────────────────────────────────────────
-- IGI's stock is the SUM of production batches, never an overwritten quantity cell.
-- Nothing is ever destroyed, so it stays visible what arrived when.

CREATE TABLE IF NOT EXISTS public.igi_batches (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id    uuid        NOT NULL REFERENCES public.igi_models(id) ON DELETE CASCADE,
  qty         integer     NOT NULL CHECK (qty > 0),
  batch_date  date        NOT NULL,
  reference   text,
  note        text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  created_by  uuid        REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_igi_batches_model ON public.igi_batches (model_id);

-- ─── 4. igi_visits ──────────────────────────────────────────────────────────
-- One movement: sortie (out) then retour (back, certified). Two movements on the same
-- day are two rows — visit_no is the identity, visit_date is not unique.
--
-- visit_date is `date`, not timestamptz, on purpose: a movement is a day, and timezone
-- conversion would let one drift across midnight into the wrong day.

CREATE TABLE IF NOT EXISTS public.igi_visits (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_no      integer     NOT NULL UNIQUE,
  visit_date    date        NOT NULL,
  -- requested — sent to IGI, on their To do
  -- issued    — IGI typed what they actually made (fewer than asked is normal)
  -- closed    — LoveLab confirmed the return
  status        text        NOT NULL DEFAULT 'requested'
                            CHECK (status IN ('requested', 'issued', 'closed')),
  requested_at  timestamptz,
  issued_at     timestamptz,
  closed_at     timestamptz,
  -- Set ONLY on imported historical movements where IGI recorded a daily total with no
  -- model detail (16 Jun – 28 Jul 2026, 3 245 certificates over 9 movements). Such a
  -- visit has a total and zero lines, so it can never be absorbed into a per-model
  -- figure. When the movements are reconstructed, lines are added and this is cleared.
  unattributed_total integer CHECK (unattributed_total IS NULL OR unattributed_total >= 0),
  -- Four movements in the source file carry the wrong year (2016, 2024, 2014, 2022).
  -- The date is kept exactly as written and flagged; the reporting month is inherited
  -- from the preceding sound visit at read time. See monthOf() in lib/igi/derive.js.
  date_suspect  boolean     NOT NULL DEFAULT false,
  note          text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid        REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_igi_visits_status ON public.igi_visits (status);
CREATE INDEX IF NOT EXISTS idx_igi_visits_date   ON public.igi_visits (visit_date);

-- ─── 5. igi_visit_lines ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.igi_visit_lines (
  id            uuid    PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id      uuid    NOT NULL REFERENCES public.igi_visits(id) ON DELETE CASCADE,
  model_id      uuid    NOT NULL REFERENCES public.igi_models(id) ON DELETE RESTRICT,
  qty_requested integer NOT NULL CHECK (qty_requested >= 0),
  -- Null until IGI confirms. Fewer than requested is normal, not an error.
  qty_issued    integer CHECK (qty_issued IS NULL OR qty_issued >= 0),
  -- Null until LoveLab confirms the return.
  qty_received  integer CHECK (qty_received IS NULL OR qty_received >= 0),
  UNIQUE (visit_id, model_id)
);

CREATE INDEX IF NOT EXISTS idx_igi_visit_lines_visit ON public.igi_visit_lines (visit_id);
CREATE INDEX IF NOT EXISTS idx_igi_visit_lines_model ON public.igi_visit_lines (model_id);

-- ─── 6. igi_descriptions ────────────────────────────────────────────────────
-- The mapping table. LoveLab's own software returns free text with no product code,
-- id or SKU — only `description` and `total_pcs`. So each description is linked to a
-- model once, by hand. Many descriptions may point at one model.
--
-- The text is stored exactly as the API returns it, warts included: the live data
-- holds both 'IGI MULTIFIVE0.25' (no space) and 'IGI MULTIFIVE 0.50' (with space).
-- Matching is exact-string only — see lib/igi/syncShelf.js for why.

CREATE TABLE IF NOT EXISTS public.igi_descriptions (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  description    text        NOT NULL UNIQUE,
  -- Null means "seen in the feed, still needs a human". Never guessed at.
  model_id       uuid        REFERENCES public.igi_models(id) ON DELETE SET NULL,
  -- certificate — an IGI certificate line, belongs to a model
  -- packaging   — merely has IGI in the name (ENVELOP PINK IGI and such)
  -- in_house    — LoveLab's own certificates, a separate product line, out of scope
  -- ignore      — deliberately parked
  -- Only 'certificate' rows with a null model_id are "needs a human". The other
  -- three are settled answers, so they never pollute the unmatched queue.
  kind           text        NOT NULL DEFAULT 'certificate'
                             CHECK (kind IN ('certificate', 'packaging', 'in_house', 'ignore')),
  first_seen_at  timestamptz NOT NULL DEFAULT now(),
  last_seen_at   timestamptz,
  linked_by      uuid        REFERENCES public.profiles(id) ON DELETE SET NULL,
  CONSTRAINT igi_descriptions_model_only_for_certificates
    CHECK (model_id IS NULL OR kind = 'certificate')
);

CREATE INDEX IF NOT EXISTS idx_igi_descriptions_model ON public.igi_descriptions (model_id);

-- ─── 7. igi_shelf_snapshots ─────────────────────────────────────────────────
-- A dated snapshot of what LoveLab's software reported, one row per description per
-- run. Yesterday minus today is what got packed — consumption measured with nobody
-- typing anything.
--
-- Keyed on the description rather than the model so the snapshot stays a faithful
-- record of what the ERP actually said, including descriptions not yet mapped.

CREATE TABLE IF NOT EXISTS public.igi_shelf_snapshots (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_date date        NOT NULL,
  description   text        NOT NULL,
  total_pcs     integer     NOT NULL CHECK (total_pcs >= 0),
  model_id      uuid        REFERENCES public.igi_models(id) ON DELETE SET NULL,
  captured_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (snapshot_date, description)
);

CREATE INDEX IF NOT EXISTS idx_igi_shelf_snapshots_date
  ON public.igi_shelf_snapshots (snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_igi_shelf_snapshots_model
  ON public.igi_shelf_snapshots (model_id, snapshot_date DESC);

-- ─── 8. igi_receipts ────────────────────────────────────────────────────────
-- Our half of the idempotency contract for the write-back endpoint that LoveLab IT
-- has yet to build. Same `reference` sent twice — a retry, a timeout, a double click —
-- must not add the stock twice. Without this you get phantom stock nobody notices
-- for months.

CREATE TABLE IF NOT EXISTS public.igi_receipts (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  visit_id   uuid        NOT NULL REFERENCES public.igi_visits(id) ON DELETE CASCADE,
  reference  text        NOT NULL UNIQUE,
  status     text        NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'applied', 'failed')),
  posted_at  timestamptz,
  response   jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_igi_receipts_visit ON public.igi_receipts (visit_id);

-- ─── 9. Row level security ──────────────────────────────────────────────────
-- The API routes use the service-role client and enforce authorization in JS
-- (app/api/_lib/access.js), so these policies are defence-in-depth. They are written
-- to make the asymmetry structural: there is deliberately NO policy granting IGI any
-- access to igi_shelf_snapshots, so a mistake in a route cannot leak LoveLab's shelf.

ALTER TABLE public.igi_models          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_batches         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_visits          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_visit_lines     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_descriptions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_shelf_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.igi_receipts        ENABLE ROW LEVEL SECURITY;

-- Admin: full access everywhere.
DROP POLICY IF EXISTS "Admin full access on igi_models" ON public.igi_models;
CREATE POLICY "Admin full access on igi_models" ON public.igi_models
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_batches" ON public.igi_batches;
CREATE POLICY "Admin full access on igi_batches" ON public.igi_batches
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_visits" ON public.igi_visits;
CREATE POLICY "Admin full access on igi_visits" ON public.igi_visits
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_visit_lines" ON public.igi_visit_lines;
CREATE POLICY "Admin full access on igi_visit_lines" ON public.igi_visit_lines
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_descriptions" ON public.igi_descriptions;
CREATE POLICY "Admin full access on igi_descriptions" ON public.igi_descriptions
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_shelf_snapshots" ON public.igi_shelf_snapshots;
CREATE POLICY "Admin full access on igi_shelf_snapshots" ON public.igi_shelf_snapshots
  USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admin full access on igi_receipts" ON public.igi_receipts;
CREATE POLICY "Admin full access on igi_receipts" ON public.igi_receipts
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- IGI: reads the models they produce and the movements addressed to them, and adds
-- their own production batches. They never see igi_shelf_snapshots or igi_receipts.
DROP POLICY IF EXISTS "IGI can read igi_models" ON public.igi_models;
CREATE POLICY "IGI can read igi_models" ON public.igi_models
  FOR SELECT TO authenticated USING (public.is_igi() AND state = 'in_use');

DROP POLICY IF EXISTS "IGI can read igi_visits" ON public.igi_visits;
CREATE POLICY "IGI can read igi_visits" ON public.igi_visits
  FOR SELECT TO authenticated USING (public.is_igi());

DROP POLICY IF EXISTS "IGI can read igi_visit_lines" ON public.igi_visit_lines;
CREATE POLICY "IGI can read igi_visit_lines" ON public.igi_visit_lines
  FOR SELECT TO authenticated USING (public.is_igi());

DROP POLICY IF EXISTS "IGI can read igi_batches" ON public.igi_batches;
CREATE POLICY "IGI can read igi_batches" ON public.igi_batches
  FOR SELECT TO authenticated USING (public.is_igi());

DROP POLICY IF EXISTS "IGI can add igi_batches" ON public.igi_batches;
CREATE POLICY "IGI can add igi_batches" ON public.igi_batches
  FOR INSERT TO authenticated WITH CHECK (public.is_igi());

-- ─── 10. Column grants ──────────────────────────────────────────────────────
-- Row level security cannot hide a column, only a row. IGI needs to read
-- igi_models, and shelf_min lives on it — so without this they could read the
-- level at which LoveLab decides their own shelf is low, which is a hint at how
-- fast it empties. Column grants are the only mechanism that closes that.
--
-- pool_min stays readable: it is IGI's own alert level, on their own stock.
--
-- The app itself reads through the service-role client, which bypasses both
-- policies and grants, so the LoveLab screens are unaffected.

REVOKE SELECT ON public.igi_models FROM authenticated;
GRANT SELECT (
  id, serial, serial_full, name, igi_name, stones, carat, shape, spec,
  state, qty_ordered, pool_min, sort_order, created_at, updated_at
) ON public.igi_models TO authenticated;

-- Who recorded each half of a movement.
--
-- Until IGI have logins, LoveLab records both sides themselves — which is what
-- happens physically anyway, since LoveLab carries the bracelets across the
-- road. Once IGI start entering their own production, a quantity LoveLab typed
-- on their behalf and one IGI typed themselves are different kinds of evidence,
-- and the history should be able to say which.

ALTER TABLE public.igi_visits
  ADD COLUMN IF NOT EXISTS issued_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.igi_visits
  ADD COLUMN IF NOT EXISTS received_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.igi_visits.issued_by IS
  'Who recorded what IGI actually produced. May be LoveLab acting on IGI''s behalf.';

COMMENT ON COLUMN public.igi_visits.received_by IS
  'Who confirmed the certificates came back. Always LoveLab.';

-- What IGI may write, and the one thing they must never write.
--
-- Phase 1 gave IGI read access to the models they produce, the movements sent
-- to them and their own batches. This adds the three writes their portal needs,
-- each narrowed to a single column where row level security alone cannot do it.

-- ─── 1. Recording what they produced ────────────────────────────────────────
-- The one transition IGI may perform: a movement waiting on them becomes one
-- that is ready to receive. They cannot cancel it, receive it, or reopen it.

DROP POLICY IF EXISTS "IGI can record what they made" ON public.igi_visits;
CREATE POLICY "IGI can record what they made" ON public.igi_visits
  FOR UPDATE TO authenticated
  USING (public.is_igi() AND status = 'requested')
  WITH CHECK (public.is_igi() AND status = 'issued');

DROP POLICY IF EXISTS "IGI can set the quantity made" ON public.igi_visit_lines;
CREATE POLICY "IGI can set the quantity made" ON public.igi_visit_lines
  FOR UPDATE TO authenticated
  USING (public.is_igi() AND EXISTS (
    SELECT 1 FROM public.igi_visits v
     WHERE v.id = visit_id AND v.status = 'requested'))
  WITH CHECK (public.is_igi());

-- Row level security decides which ROWS may be updated, never which COLUMNS.
-- Without the grant below, the policy above would also let IGI rewrite
-- qty_requested — that is, quietly change what LoveLab asked for.
REVOKE UPDATE ON public.igi_visit_lines FROM authenticated;
GRANT UPDATE (qty_issued) ON public.igi_visit_lines TO authenticated;

-- ─── 2. Their own alert level ───────────────────────────────────────────────
-- Two alert rules, one owner each. pool_min is IGI's, on their own stock.
-- shelf_min is LoveLab's and is not even readable here (see the 20260828120000
-- migration), let alone writable.

DROP POLICY IF EXISTS "IGI can set their own alert level" ON public.igi_models;
CREATE POLICY "IGI can set their own alert level" ON public.igi_models
  FOR UPDATE TO authenticated
  USING (public.is_igi() AND state = 'in_use')
  WITH CHECK (public.is_igi());

REVOKE UPDATE ON public.igi_models FROM authenticated;
GRANT UPDATE (pool_min) ON public.igi_models TO authenticated;

-- ─── 3. Closing a door that was already open ────────────────────────────────
-- Not an IGI change, but it is what makes every IGI rule above hold.
--
-- The profiles policy is FOR UPDATE USING (auth.uid() = id) with no column
-- restriction, so any signed-in account could rewrite its own row through the
-- public API — including `role`, and now `is_igi`. An IGI account could
-- therefore clear its own flag and walk straight past the containment in
-- lib/supabase/middleware.js; an agent could make themselves an admin.
--
-- Nothing in the application writes to profiles through the RLS-scoped client
-- (every path uses the service role, which is unaffected by grants), so
-- withdrawing this changes no behaviour and removes the escalation.

REVOKE UPDATE ON public.profiles FROM authenticated;

-- ─── 2 of 3 · The opening balances ─────────────────────────────────────
--
-- IGI's file as of 27 August 2026. Keyed on the serial, the movement number
-- and the description, so a second run changes nothing.

-- Models that IGI have numbered.
INSERT INTO public.igi_models
  (serial, serial_full, name, igi_name, stones, carat, shape, spec, state, qty_ordered, sort_order)
VALUES
  ('LGAJ6529', 'LGAJ65292505', 'Cuty-Cubix / Moonlight Long', 'Cuty - Cubix', '1', 0.05, 'Round', NULL, 'in_use', 12250, 2),
  ('LGAJ6530', 'LGAJ65302505', 'Cuty-Cubix / Sienna 1 / Moonlight Original / Moonlight Long', 'Cuty - Cubix', '1', 0.1, 'Round', NULL, 'in_use', 12250, 3),
  ('LGAJ6531', 'LGAJ65312505', 'Cuty-Cubix / Sienna 1 / Moonlight Original', 'Cuty - Cubix', '1', 0.2, 'Round', NULL, 'in_use', 500, 4),
  ('LGAJ6532', 'LGAJ65322505', 'Cuty-Cubix / Sienna 1 / Moonlight Original / Moonlight Long', 'Cuty - Cubix', '1', 0.3, 'Round', NULL, 'in_use', 250, 5),
  ('LGAJ6533', 'LGAJ65332505', 'Multi Three', 'Multi Three', '3', 0.15, 'Round', NULL, 'in_use', 3550, 6),
  ('LGAJ6534', 'LGAJ65342505', 'Multi Three', 'Multi Three', '3', 0.3, 'Round', NULL, 'in_use', 2000, 7),
  ('LGAJ6535', 'LGAJ65352505', 'Multi Three', 'Multi Three', '3', 0.6, 'Round', NULL, 'in_use', 100, 8),
  ('LGAJ6536', 'LGAJ65362505', 'Multi Three', 'Multi Three', '3', 0.9, 'Round', NULL, 'in_use', 100, 9),
  ('LGAJ6537', 'LGAJ65372505', 'Multi Four / Sienna 4', 'Multi Four', '4', 0.2, 'Round', NULL, 'in_use', 500, 10),
  ('LGAJ6538', 'LGAJ65382505', 'Multi Four / Sienna 4', 'Multi Four', '4', 0.4, 'Round', NULL, 'in_use', 500, 11),
  ('LGAJ6539', 'LGAJ65392505', 'Multi Five / Sienna 5', 'Multi Five', '5', 0.25, 'Round', NULL, 'in_use', 500, 12),
  ('LGAJ6540', 'LGAJ65402505', 'Multi Five / Sienna 5', 'Multi Five', '5', 0.5, 'Round', NULL, 'in_use', 500, 13),
  ('LGAJ6541', 'LGAJ65412505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Cushion', NULL, 'in_use', 250, 14),
  ('LGAJ6542', 'LGAJ65422505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Cushion', NULL, 'in_use', 250, 15),
  ('LGAJ6543', 'LGAJ65432505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Long Cushion', NULL, 'in_use', 250, 16),
  ('LGAJ6544', 'LGAJ65442505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Long Cushion', NULL, 'in_use', 250, 17),
  ('LGAJ6545', 'LGAJ65452505', 'Shapy Shine', 'Shapy Shine', '1', 0.1, 'Emerald', NULL, 'in_use', 2000, 18),
  ('LGAJ6546', 'LGAJ65462505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Emerald', NULL, 'in_use', 500, 19),
  ('LGAJ6547', 'LGAJ65472505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Emerald', NULL, 'in_use', 250, 20),
  ('LGAJ6548', 'LGAJ65482505', 'Matchy Fancy', 'Matchy Fancy', '2', 0.6, 'Emerald', NULL, 'in_use', 500, 21),
  ('LGAJ6549', 'LGAJ65492505', 'Matchy Fancy', 'Matchy Fancy', '2', 1, 'Emerald', NULL, 'in_use', 250, 22),
  ('LGAJ6550', 'LGAJ65502505', 'Shapy Shine', 'Shapy Shine', '1', 0.1, 'Heart', NULL, 'in_use', 2000, 23),
  ('LGAJ6551', 'LGAJ65512505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Heart', NULL, 'in_use', 500, 24),
  ('LGAJ6552', 'LGAJ65522505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Heart', NULL, 'in_use', 250, 25),
  ('LGAJ6553', 'LGAJ65532505', 'Matchy Fancy', 'Matchy Fancy', '2', 0.6, 'Heart', NULL, 'in_use', 500, 26),
  ('LGAJ6554', 'LGAJ65542505', 'Matchy Fancy', 'Matchy Fancy', '2', 1, 'Heart', NULL, 'in_use', 250, 27),
  ('LGAJ6555', 'LGAJ65552505', 'Shapy Shine', 'Shapy Shine', '1', 0.1, 'Marquise', NULL, 'in_use', 2000, 28),
  ('LGAJ6556', 'LGAJ65562505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Marquise', NULL, 'in_use', 500, 29),
  ('LGAJ6557', 'LGAJ65572505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Marquise', NULL, 'in_use', 250, 30),
  ('LGAJ6558', 'LGAJ65582505', 'Shapy Shine', 'Shapy Shine', '1', 0.1, 'Oval', NULL, 'in_use', 2000, 31),
  ('LGAJ6559', 'LGAJ65592505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Oval', NULL, 'in_use', 500, 32),
  ('LGAJ6560', 'LGAJ65602505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Oval', NULL, 'in_use', 250, 33),
  ('LGAJ6561', 'LGAJ65612505', 'Shapy Shine', 'Shapy Shine', '1', 0.1, 'Pear', NULL, 'in_use', 2000, 34),
  ('LGAJ6562', 'LGAJ65622505', 'Shapy Shine', 'Shapy Shine', '1', 0.3, 'Pear', NULL, 'in_use', 500, 35),
  ('LGAJ6563', 'LGAJ65632505', 'Shapy Shine', 'Shapy Shine', '1', 0.5, 'Pear', NULL, 'in_use', 250, 36),
  ('LGAJ6564', 'LGAJ65642505', 'Matchy Fancy', 'Matchy Fancy', '2', 0.6, 'Pear', NULL, 'in_use', 500, 37),
  ('LGAJ6565', 'LGAJ65652505', 'Matchy Fancy', 'Matchy Fancy', '2', 1, 'Pear', NULL, 'in_use', 250, 38),
  ('LGAJ6566', 'LGAJ65662607', 'Multi Moonlight', 'HALO', '3', 0.2, 'Round', 'D/E', 'in_use', 500, 39),
  ('LGAJ6567', 'LGAJ65672607', 'Multi Moonlight', 'HALO', '3', 0.4, 'Round', 'D/E', 'in_use', 500, 40),
  ('LGAJ6568', 'LGAJ65682607', 'ZAHA', 'ZAHA', '1', 0.3, 'Marquise', 'D/E', 'in_use', 500, 41),
  ('LGAJ6569', 'LGAJ65692607', 'FLOWER MARQ', 'LUMA', '4', 0.4, 'Marquise', 'D/E', 'in_use', 500, 42),
  ('LGAJ6570', 'LGAJ65702607', 'FLOWER HEART', 'LUVA', '4', 0.4, 'Heart', 'D/E', 'in_use', 500, 43),
  ('LGAJ6571', 'LGAJ65712607', 'LINEA', 'LINEA', '3', 0.3, 'Princess', 'D/E', 'in_use', 500, 44),
  ('LGAJ6572', 'LGAJ65722607', 'LINEA', 'LINEA', '5', 0.5, 'Princess', 'D/E', 'in_use', 500, 45),
  ('LGAJ6573', 'LGAJ65732607', 'SIENNA', 'SIENNA', '2', 0.2, 'Pear', 'D/E', 'in_use', 500, 46),
  ('LGAJ6574', 'LGAJ65742607', 'RIVIERA', 'RIVIERA', '8', 0.8, 'Round', 'D/E', 'in_use', 500, 47),
  ('LGAJ6575', 'LGAJ65752607', 'RIVIERA', 'RIVIERA', '8', 0.4, 'Round', 'D/E', 'in_use', 500, 48),
  ('LGAJ6576', 'LGAJ65762607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.05, 'Round', 'Fancy Vivid Yellow', 'in_use', 833, 49),
  ('LGAJ6577', 'LGAJ65772607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.05, 'Round', 'Fancy Vivid Blue', 'in_use', 833, 50),
  ('LGAJ6578', 'LGAJ65782607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.05, 'Round', 'Fancy Vivid Pink', 'in_use', 833, 51),
  ('LGAJ6579', 'LGAJ65792607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.15, 'Round', 'Fancy Vivid Yellow', 'in_use', 500, 52),
  ('LGAJ6580', 'LGAJ65802607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.15, 'Round', 'Fancy Vivid Blue', 'in_use', 500, 53),
  ('LGAJ6581', 'LGAJ65812607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.15, 'Round', 'Fancy Vivid Pink', 'in_use', 500, 54),
  ('LGAJ6582', 'LGAJ65822607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.1, 'Round', 'Fancy Vivid Yellow', 'in_use', 500, 55),
  ('LGAJ6583', 'LGAJ65832607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.1, 'Round', 'Fancy Vivid Blue', 'in_use', 500, 56),
  ('LGAJ6584', 'LGAJ65842607', 'CUTY FANCY COLOR', 'CUTY FANCY COLOR', '1', 0.1, 'Round', 'Fancy Vivid Pink', 'in_use', 500, 57),
  ('LGAJ6585', 'LGAJ65852607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.3, 'Round', 'Fancy Vivid Yellow', 'in_use', 500, 58),
  ('LGAJ6586', 'LGAJ65862607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.3, 'Round', 'Fancy Vivid Blue', 'in_use', 500, 59),
  ('LGAJ6587', 'LGAJ65872607', 'THREE FANCY COLOR', 'THREE FANCY COLOR', '3', 0.3, 'Round', 'Fancy Vivid Pink', 'in_use', 500, 60),
  ('LGAJ6588', 'LGAJ65882607', '—', '—', '4', 0.8, 'Rd', NULL, 'reserved', NULL, 61),
  ('LGAJ6589', 'LGAJ65892607', '—', '—', '4', 1.2, 'Rd', NULL, 'reserved', NULL, 62),
  ('LGAJ6590', 'LGAJ65902607', '—', '—', '5', 1, 'Rd', NULL, 'reserved', NULL, 63),
  ('LGAJ6591', 'LGAJ65912607', '—', '—', '5', 1.5, 'Rd', NULL, 'reserved', NULL, 64),
  ('LGAJ6592', 'LGAJ65922607', '—', '—', '6', 0.3, 'Rd', NULL, 'reserved', NULL, 65),
  ('LGAJ6593', 'LGAJ65932607', '—', '—', '6', 0.6, 'Rd', NULL, 'reserved', NULL, 66),
  ('LGAJ6594', 'LGAJ65942607', '—', '—', '6', 1.2, 'Rd', NULL, 'reserved', NULL, 67),
  ('LGAJ6595', 'LGAJ65952607', '—', '—', '12', 0.6, 'Rd', NULL, 'reserved', NULL, 68),
  ('LGAJ6596', 'LGAJ65962607', '—', '—', '12', 1.2, 'Rd', NULL, 'reserved', NULL, 69),
  ('LGAJ6597', 'LGAJ65972607', 'A', 'A', '6+1', 1.5, 'Rd', NULL, 'reserved', NULL, 70),
  ('LGAJ6598', 'LGAJ65982607', 'B', 'B', '6+1', 0.8, 'Rd', NULL, 'reserved', NULL, 71),
  ('LGAJ6599', 'LGAJ65992607', 'C', 'C', '6+1', 0.65, 'Rd', NULL, 'reserved', NULL, 72),
  ('LGAJ6600', 'LGAJ66002607', 'D', 'D', '3+2', 1.3, 'Rd', NULL, 'reserved', NULL, 73),
  ('LGAJ6601', 'LGAJ66012607', 'E', 'E', '3+2', 0.8, 'Rd', NULL, 'reserved', NULL, 74),
  ('LGAJ6602', 'LGAJ66022607', 'F', 'F', '3+2', 0.4, 'Rd', NULL, 'reserved', NULL, 75),
  ('LGAJ6603', 'LGAJ66032607', 'LONG MULTI ML', 'LONG MULTI ML', '5', 0.3, 'Rd', '4 X 0,05 1 X 0,10', 'in_use', 500, 76),
  ('LGAJ6604', 'LGAJ66042607', 'LONG MULTI ML', 'LONG MULTI ML', '7', 0.4, 'Rd', '6 X 0,05 1 X 0,10', 'in_use', 500, 77)
ON CONFLICT (serial) WHERE serial IS NOT NULL DO NOTHING;

-- Models LoveLab have asked for that IGI have not numbered yet.
INSERT INTO public.igi_models (name, stones, carat, shape, spec, state, sort_order)
SELECT 'Full Moonlight', '1', 0.5, 'Round', 'new certificate needed', 'awaiting_serial', 1000
WHERE NOT EXISTS (
  SELECT 1 FROM public.igi_models
   WHERE state = 'awaiting_serial' AND name = 'Full Moonlight' AND carat = 0.5
);
INSERT INTO public.igi_models (name, stones, carat, shape, spec, state, sort_order)
SELECT 'Full Moonlight', '1', 0.7, 'Round', 'new certificate needed', 'awaiting_serial', 1001
WHERE NOT EXISTS (
  SELECT 1 FROM public.igi_models
   WHERE state = 'awaiting_serial' AND name = 'Full Moonlight' AND carat = 0.7
);
INSERT INTO public.igi_models (name, stones, carat, shape, spec, state, sort_order)
SELECT 'Full Moonlight', '1', 1, 'Round', 'new certificate needed', 'awaiting_serial', 1002
WHERE NOT EXISTS (
  SELECT 1 FROM public.igi_models
   WHERE state = 'awaiting_serial' AND name = 'Full Moonlight' AND carat = 1
);

-- Every description LoveLab's own software returns, classified once so the
-- "needs a human" queue starts empty.
INSERT INTO public.igi_descriptions (description, model_id, kind)
VALUES
  ('BUTTER PAPER- LL NOTES FRENCH', NULL, 'ignore'),
  ('BUTTER PAPER-LL NOTES ENGLISH', NULL, 'ignore'),
  ('BUTTER PAPER-LL NOTES ITALIAN', NULL, 'ignore'),
  ('CATALOGUE FR NEW', NULL, 'ignore'),
  ('CATALOGUE GERM', NULL, 'ignore'),
  ('CATALOGUES', NULL, 'ignore'),
  ('CATALOGUES ENG', NULL, 'ignore'),
  ('DHL BOXES NR 2', NULL, 'ignore'),
  ('DHL BOXES NR 4', NULL, 'ignore'),
  ('DHL BOXES NR 5', NULL, 'ignore'),
  ('DHL ENVELOPPES', NULL, 'ignore'),
  ('ENVELOP PINK IGI', NULL, 'packaging'),
  ('ENVELOPE BLACK IGI', NULL, 'packaging'),
  ('ENVELOPPE BLACK', NULL, 'ignore'),
  ('ENVELOPPE PINK', NULL, 'ignore'),
  ('IGI 0.05 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 'certificate'),
  ('IGI 0.05*3 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 'certificate'),
  ('IGI 0.10 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 'certificate'),
  ('IGI 0.10*3 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 'certificate'),
  ('IGI 0.20*3 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 'certificate'),
  ('IGI 0.30*3 CERTIFICATE', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 'certificate'),
  ('IGI CUTY 0.20', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 'certificate'),
  ('IGI CUTY 0.30', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 'certificate'),
  ('IGI EMERALD 0.10', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 'certificate'),
  ('IGI EMERALD 0.50', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547'), 'certificate'),
  ('IGI HEART 0.10', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 'certificate'),
  ('IGI HEART 0.50', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6552'), 'certificate'),
  ('IGI MARQUISE 0.10', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 'certificate'),
  ('IGI MARQUISE 0.30', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6556'), 'certificate'),
  ('IGI MATCHY FANCY HEART 0.60', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6553'), 'certificate'),
  ('IGI MULTI FOUR 0.20', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 'certificate'),
  ('IGI MULTI FOUR 0.40', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 'certificate'),
  ('IGI MULTIFIVE 0.50', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 'certificate'),
  ('IGI MULTIFIVE0.25', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 'certificate'),
  ('IGI OVAL 0.10', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 'certificate'),
  ('IGI OVAL 0.50', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 'certificate'),
  ('IGI PEAR 0.10', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 'certificate'),
  ('IGI PEAR 0.30', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 'certificate'),
  ('IGI PEAR 0.50', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563'), 'certificate'),
  ('IGI SHAPYSHINE 0.30 OVAL', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 'certificate'),
  ('IGI SHAPYSHINE EMERALD 0.30', (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 'certificate'),
  ('INHOUSE CERTIFICATE  4X 0.05 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE  CUTY 0,05 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE  CUTY 0,10 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE  CUTY 0,20 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE  CUTY 0,30 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE 4 X 0.10 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE 5 X 0.05 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE 5 X 0.10 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE EMERALD 0,10', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE EMPTY GREY', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE HEART 0,10', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE MARQUISE 0,10', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE OVAL 0,10', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE PEAR 0,10', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE TRIPLY 0,15 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE TRIPLY 0,30 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE TRIPLY 0,60 WHITE', NULL, 'in_house'),
  ('INHOUSE CERTIFICATE TRIPLY 0,90 WHITE', NULL, 'in_house'),
  ('INVOICE ENVELOPPES BLACK', NULL, 'ignore'),
  ('INVOICE ENVELOPPES WHITE', NULL, 'ignore'),
  ('J &J PINK IGI', NULL, 'packaging'),
  ('JOE & JUICE BLACK', NULL, 'ignore'),
  ('JOE & JUICE PINK', NULL, 'ignore'),
  ('LOVE LAB FOLDER ENGLISH', NULL, 'ignore'),
  ('LOVE LAB PINK FOLDER FRANCE', NULL, 'ignore'),
  ('LOVE LAB PINK FOLDER GERMAN', NULL, 'ignore'),
  ('LOVELAB VITRINE', NULL, 'ignore'),
  ('MAGNETIC BOX  5 ROWS PINK', NULL, 'ignore'),
  ('MAGNETIC BOX 2 ROWS PINK', NULL, 'ignore'),
  ('MAGNETIC BOX SMALL BLACK', NULL, 'ignore'),
  ('MAGNETIC BOX SMALL PINK', NULL, 'ignore'),
  ('MOTHERS DAY CARDS', NULL, 'ignore'),
  ('NEW PINK ENVELOPPES', NULL, 'ignore'),
  ('NEW VITRINE HERMES', NULL, 'ignore'),
  ('PILLOW  PINK BIG', NULL, 'ignore'),
  ('PILLOW BLACK BIG', NULL, 'ignore'),
  ('PILLOW BLACK SMALL', NULL, 'ignore'),
  ('PILLOW GREY SMALL', NULL, 'ignore'),
  ('PILLOW PINK SMALL', NULL, 'ignore'),
  ('PILLOW WHITE BIG', NULL, 'ignore'),
  ('PILLOW WHITE SMALL', NULL, 'ignore'),
  ('PRESENTATION BLACK BOOK', NULL, 'ignore'),
  ('PRESENTATION BOXES LOVELAB', NULL, 'ignore'),
  ('SHOEBOX 2 ROWS BLACK', NULL, 'ignore'),
  ('SHOEBOX 2 ROWS PINK', NULL, 'ignore'),
  ('SHOEBOX 3 ROWS BLACK', NULL, 'ignore'),
  ('SHOEBOX 3 ROWS PINK', NULL, 'ignore'),
  ('SHOEBOX 5 ROWS PINK', NULL, 'ignore'),
  ('Shopping bag BIG BLACK', NULL, 'ignore'),
  ('Shopping Bag BIG PINK', NULL, 'ignore'),
  ('Shopping Bag SMALL BLACK', NULL, 'ignore'),
  ('Shopping Bag SMALL PINK', NULL, 'ignore'),
  ('STICKERS LOVELAB', NULL, 'ignore'),
  ('THANK YOU CARD BIG BLACK', NULL, 'ignore'),
  ('THANK YOU CARD BIG BLACK ENGLISH 90X85', NULL, 'ignore'),
  ('THANK YOU CARD BIG PINK', NULL, 'ignore'),
  ('THANK YOU CARD BIG PINK ENGLISH 90X85', NULL, 'ignore'),
  ('THANK YOU CARD FRENCH PINK 90 X 85', NULL, 'ignore'),
  ('THANK YOU CARDS BLACK FRENCG 85X85', NULL, 'ignore'),
  ('THANK YOU CARDS BLACKFRENCH  90X85', NULL, 'ignore'),
  ('THANK YOU CARDS ENGLISH BLACK', NULL, 'ignore'),
  ('THANK YOU CARDS ENGLISH BLACK 85X85', NULL, 'ignore'),
  ('THANK YOU CARDS ENGLISH PINK', NULL, 'ignore'),
  ('THANK YOU CARDS ENGLISH PINK 85X85', NULL, 'ignore'),
  ('THANK YOU CARDS FRENCH PINK85X85', NULL, 'ignore'),
  ('THANK YOU CARDS ITALIAN BLACK', NULL, 'ignore'),
  ('THANK YOU CARDS ITALIAN BLACK 85X85', NULL, 'ignore'),
  ('THANK YOU CARDS ITALIAN PINK', NULL, 'ignore'),
  ('THANK YOU CARDS ITALIAN PINK 85X85', NULL, 'ignore'),
  ('TOTEBAGS 2026', NULL, 'ignore'),
  ('UNIVERSAL SOCKET', NULL, 'ignore'),
  ('VALENTINE BUTTER PAPER', NULL, 'ignore'),
  ('VALENTINE JOE JUICE', NULL, 'ignore'),
  ('VALENTINE TY CARDS', NULL, 'ignore'),
  ('VALETINE INHOUSE CERT 0,10', NULL, 'in_house')
ON CONFLICT (description) DO NOTHING;

-- The original commissioned run, one batch per model. IGI's stock is the sum
-- of these, so nothing is ever overwritten.
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 12250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 12250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 3550, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 100, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 100, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6541'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6541') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6542'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6542') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6543'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6543') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6544'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6544') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6548'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6548') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6549'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6549') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6552'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6552') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6553'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6553') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6554'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6554') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6556'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6556') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6557'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6557') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 2000, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6565'), 250, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6565') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6566'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6566') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6567'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6567') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6568'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6568') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6569'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6569') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6570'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6570') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6571'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6571') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6572'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6572') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6573'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6573') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6574'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6574') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6575'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6575') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6576'), 833, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6576') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6577'), 833, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6577') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6578'), 833, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6578') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6579'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6579') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6580'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6580') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6581'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6581') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6582'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6582') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6583'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6583') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6584'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6584') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6585'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6585') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6586'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6586') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6587'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6587') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6603'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6603') AND reference = 'initial order');
INSERT INTO public.igi_batches (model_id, qty, batch_date, reference)
SELECT (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6604'), 500, '2026-08-27', 'initial order'
WHERE NOT EXISTS (SELECT 1 FROM public.igi_batches
   WHERE model_id = (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6604') AND reference = 'initial order');

-- The 23 movements. Nine of them carry a total with no models — those are the
-- certificates IGI issued between 16 June and 28 July without recording which
-- model they belonged to. They stay visible instead of being absorbed.
INSERT INTO public.igi_visits (visit_no, visit_date, status, date_suspect, unattributed_total, closed_at)
VALUES
  (1, '2026-05-05', 'closed', false, NULL, '2026-05-05'::date + time '12:00'),
  (2, '2026-05-07', 'closed', false, NULL, '2026-05-07'::date + time '12:00'),
  (3, '2026-05-08', 'closed', false, NULL, '2026-05-08'::date + time '12:00'),
  (4, '2026-05-13', 'closed', false, NULL, '2026-05-13'::date + time '12:00'),
  (5, '2026-05-28', 'closed', false, NULL, '2026-05-28'::date + time '12:00'),
  (6, '2026-06-02', 'closed', false, NULL, '2026-06-02'::date + time '12:00'),
  (7, '2026-06-10', 'closed', false, NULL, '2026-06-10'::date + time '12:00'),
  (8, '2026-06-12', 'closed', false, NULL, '2026-06-12'::date + time '12:00'),
  (9, '2016-06-01', 'closed', true, 453, '2016-06-01'::date + time '12:00'),
  (10, '2024-06-01', 'closed', true, 3, '2024-06-01'::date + time '12:00'),
  (11, '2026-07-03', 'closed', false, 694, '2026-07-03'::date + time '12:00'),
  (12, '2026-07-08', 'closed', false, 222, '2026-07-08'::date + time '12:00'),
  (13, '2026-07-10', 'closed', false, 302, '2026-07-10'::date + time '12:00'),
  (14, '2014-07-01', 'closed', true, 787, '2014-07-01'::date + time '12:00'),
  (15, '2022-07-01', 'closed', true, 15, '2022-07-01'::date + time '12:00'),
  (16, '2026-07-23', 'closed', false, 503, '2026-07-23'::date + time '12:00'),
  (17, '2026-07-28', 'closed', false, 266, '2026-07-28'::date + time '12:00'),
  (18, '2026-08-24', 'closed', false, NULL, '2026-08-24'::date + time '12:00'),
  (19, '2026-08-24', 'closed', false, NULL, '2026-08-24'::date + time '12:00'),
  (20, '2026-08-25', 'closed', false, NULL, '2026-08-25'::date + time '12:00'),
  (21, '2026-08-25', 'closed', false, NULL, '2026-08-25'::date + time '12:00'),
  (22, '2026-08-26', 'closed', false, NULL, '2026-08-26'::date + time '12:00'),
  (23, '2026-08-27', 'closed', false, NULL, '2026-08-27'::date + time '12:00')
ON CONFLICT (visit_no) DO NOTHING;

-- What each movement carried, model by model.
INSERT INTO public.igi_visit_lines (visit_id, model_id, qty_requested, qty_issued, qty_received)
VALUES
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 26, 26, 26),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 13, 13, 13),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 1), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 75, 75, 75),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 65, 65, 65),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 12, 12, 12),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 12, 12, 12),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 7, 7, 7),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 8, 8, 8),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 2), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 500, 500, 500),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 500, 500, 500),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 50, 50, 50),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 50, 50, 50),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 25, 25, 25),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 20, 20, 20),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 3), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 100, 100, 100),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 144, 144, 144),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 150, 150, 150),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 75, 75, 75),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 50, 50, 50),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 8, 8, 8),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 39, 39, 39),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 4), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 113, 113, 113),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 112, 112, 112),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 51, 51, 51),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 35, 35, 35),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 25, 25, 25),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6540'), 21, 21, 21),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 27, 27, 27),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 9, 9, 9),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 15, 15, 15),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 14, 14, 14),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 5), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 9, 9, 9),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 8, 8, 8),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 17, 17, 17),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 133, 133, 133),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 14, 14, 14),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 35, 35, 35),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 6), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 19, 19, 19),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 18, 18, 18),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 7, 7, 7),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 7, 7, 7),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 7), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 29, 29, 29),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 5, 5, 5),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6548'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6550'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6551'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6552'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6553'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6556'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6559'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 8), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6562'), 6, 6, 6),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 18), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6529'), 63, 63, 63),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 18), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 96, 96, 96),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 18), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 26, 26, 26),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 18), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 19), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 19), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6557'), 1, 1, 1),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 19), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 19), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6534'), 55, 55, 55),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 4, 4, 4),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6545'), 27, 27, 27),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6546'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6555'), 40, 40, 40),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6556'), 33, 33, 33),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6558'), 34, 34, 34),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 20), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6561'), 16, 16, 16),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 21), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6531'), 30, 30, 30),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 21), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6532'), 38, 38, 38),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 21), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6547'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 21), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6560'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 21), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6563'), 2, 2, 2),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6530'), 294, 294, 294),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6533'), 22, 22, 22),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6535'), 7, 7, 7),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6536'), 3, 3, 3),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6537'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6538'), 13, 13, 13),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 22), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6539'), 11, 11, 11),
  ((SELECT id FROM public.igi_visits WHERE visit_no = 23), (SELECT id FROM public.igi_models WHERE serial = 'LGAJ6564'), 1, 1, 1)
ON CONFLICT (visit_id, model_id) DO NOTHING;

-- One reading of LoveLab's shelf, taken from the packing-stock endpoint on
-- 2026-08-28, so the screens have a shelf figure from the first minute.
-- The nightly job writes a fresher one and the screens use the newest.
INSERT INTO public.igi_shelf_snapshots (snapshot_date, description, total_pcs, model_id)
SELECT '2026-08-28'::date, v.description, v.total_pcs, d.model_id
  FROM (VALUES
    ('BUTTER PAPER- LL NOTES FRENCH', 1902),
    ('BUTTER PAPER-LL NOTES ENGLISH', 5087),
    ('BUTTER PAPER-LL NOTES ITALIAN', 497),
    ('CATALOGUE FR NEW', 3992),
    ('CATALOGUE GERM', 49),
    ('CATALOGUES', 914),
    ('CATALOGUES ENG', 284),
    ('DHL BOXES NR 2', 40),
    ('DHL BOXES NR 4', 31),
    ('DHL BOXES NR 5', 44),
    ('DHL ENVELOPPES', 200),
    ('ENVELOP PINK IGI', 2893),
    ('ENVELOPE BLACK IGI', 1035),
    ('ENVELOPPE BLACK', 1091),
    ('ENVELOPPE PINK', 542),
    ('IGI 0.05 CERTIFICATE', 670),
    ('IGI 0.05*3 CERTIFICATE', 52),
    ('IGI 0.10 CERTIFICATE', 1006),
    ('IGI 0.10*3 CERTIFICATE', 335),
    ('IGI 0.20*3 CERTIFICATE', 70),
    ('IGI 0.30*3 CERTIFICATE', 16),
    ('IGI CUTY 0.20', 145),
    ('IGI CUTY 0.30', 134),
    ('IGI EMERALD 0.10', 64),
    ('IGI EMERALD 0.50', 96),
    ('IGI HEART 0.10', 87),
    ('IGI HEART 0.50', 2),
    ('IGI MARQUISE 0.10', 149),
    ('IGI MARQUISE 0.30', 43),
    ('IGI MATCHY FANCY HEART 0.60', 3),
    ('IGI MULTI FOUR 0.20', 65),
    ('IGI MULTI FOUR 0.40', 126),
    ('IGI MULTIFIVE 0.50', 46),
    ('IGI MULTIFIVE0.25', 77),
    ('IGI OVAL 0.10', 138),
    ('IGI OVAL 0.50', 5),
    ('IGI PEAR 0.10', 85),
    ('IGI PEAR 0.30', 37),
    ('IGI PEAR 0.50', 4),
    ('IGI SHAPYSHINE 0.30 OVAL', 31),
    ('IGI SHAPYSHINE EMERALD 0.30', 18),
    ('INHOUSE CERTIFICATE  4X 0.05 WHITE', 209),
    ('INHOUSE CERTIFICATE  CUTY 0,05 WHITE', 841),
    ('INHOUSE CERTIFICATE  CUTY 0,10 WHITE', 2001),
    ('INHOUSE CERTIFICATE  CUTY 0,20 WHITE', 484),
    ('INHOUSE CERTIFICATE  CUTY 0,30 WHITE', 1238),
    ('INHOUSE CERTIFICATE 4 X 0.10 WHITE', 472),
    ('INHOUSE CERTIFICATE 5 X 0.05 WHITE', 230),
    ('INHOUSE CERTIFICATE 5 X 0.10 WHITE', 243),
    ('INHOUSE CERTIFICATE EMERALD 0,10', 360),
    ('INHOUSE CERTIFICATE EMPTY GREY', 91),
    ('INHOUSE CERTIFICATE HEART 0,10', 255),
    ('INHOUSE CERTIFICATE MARQUISE 0,10', 411),
    ('INHOUSE CERTIFICATE OVAL 0,10', 413),
    ('INHOUSE CERTIFICATE PEAR 0,10', 404),
    ('INHOUSE CERTIFICATE TRIPLY 0,15 WHITE', 1087),
    ('INHOUSE CERTIFICATE TRIPLY 0,30 WHITE', 998),
    ('INHOUSE CERTIFICATE TRIPLY 0,60 WHITE', 753),
    ('INHOUSE CERTIFICATE TRIPLY 0,90 WHITE', 1066),
    ('INVOICE ENVELOPPES BLACK', 445),
    ('INVOICE ENVELOPPES WHITE', 374),
    ('J &J PINK IGI', 1585),
    ('JOE & JUICE BLACK', 660),
    ('JOE & JUICE PINK', 1536),
    ('LOVE LAB FOLDER ENGLISH', 1124),
    ('LOVE LAB PINK FOLDER FRANCE', 1063),
    ('LOVE LAB PINK FOLDER GERMAN', 1125),
    ('LOVELAB VITRINE', 15),
    ('MAGNETIC BOX  5 ROWS PINK', 2),
    ('MAGNETIC BOX 2 ROWS PINK', 4),
    ('MAGNETIC BOX SMALL BLACK', 66),
    ('MAGNETIC BOX SMALL PINK', 436),
    ('MOTHERS DAY CARDS', 1193),
    ('NEW PINK ENVELOPPES', 4287),
    ('NEW VITRINE HERMES', 3),
    ('PILLOW  PINK BIG', 32),
    ('PILLOW BLACK BIG', 117),
    ('PILLOW BLACK SMALL', 117),
    ('PILLOW GREY SMALL', 212),
    ('PILLOW PINK SMALL', 35),
    ('PILLOW WHITE BIG', 135),
    ('PILLOW WHITE SMALL', 138),
    ('PRESENTATION BLACK BOOK', 95),
    ('PRESENTATION BOXES LOVELAB', 7),
    ('SHOEBOX 2 ROWS BLACK', 61),
    ('SHOEBOX 2 ROWS PINK', 97),
    ('SHOEBOX 3 ROWS BLACK', 56),
    ('SHOEBOX 3 ROWS PINK', 43),
    ('SHOEBOX 5 ROWS PINK', 16),
    ('Shopping bag BIG BLACK', 227),
    ('Shopping Bag BIG PINK', 90),
    ('Shopping Bag SMALL BLACK', 740),
    ('Shopping Bag SMALL PINK', 653),
    ('STICKERS LOVELAB', 11354),
    ('THANK YOU CARD BIG BLACK', 1195),
    ('THANK YOU CARD BIG BLACK ENGLISH 90X85', 3160),
    ('THANK YOU CARD BIG PINK', 1195),
    ('THANK YOU CARD BIG PINK ENGLISH 90X85', 2122),
    ('THANK YOU CARD FRENCH PINK 90 X 85', 67),
    ('THANK YOU CARDS BLACK FRENCG 85X85', 364),
    ('THANK YOU CARDS BLACKFRENCH  90X85', 1981),
    ('THANK YOU CARDS ENGLISH BLACK', 2032),
    ('THANK YOU CARDS ENGLISH BLACK 85X85', 1334),
    ('THANK YOU CARDS ENGLISH PINK', 2065),
    ('THANK YOU CARDS ENGLISH PINK 85X85', 3293),
    ('THANK YOU CARDS FRENCH PINK85X85', 2544),
    ('THANK YOU CARDS ITALIAN BLACK', 1133),
    ('THANK YOU CARDS ITALIAN BLACK 85X85', 781),
    ('THANK YOU CARDS ITALIAN PINK', 904),
    ('THANK YOU CARDS ITALIAN PINK 85X85', 584),
    ('TOTEBAGS 2026', 507),
    ('UNIVERSAL SOCKET', 3),
    ('VALENTINE BUTTER PAPER', 973),
    ('VALENTINE JOE JUICE', 1275),
    ('VALENTINE TY CARDS', 993),
    ('VALETINE INHOUSE CERT 0,10', 975)
  ) AS v(description, total_pcs)
  LEFT JOIN public.igi_descriptions d ON d.description = v.description
ON CONFLICT (snapshot_date, description) DO NOTHING;

-- ─── 3 of 3 · The check ────────────────────────────────────────────────
--
-- An opening balance that is quietly wrong would be inherited by every screen
-- and every invoice built on top of it, so this stops rather than warns.

DO $check$
DECLARE
  v_actual bigint;
BEGIN
  SELECT count(*) FROM public.igi_models WHERE state = 'in_use' INTO v_actual;
  IF v_actual <> 61 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'models in use', v_actual, 61;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('models in use', 34), v_actual;
  SELECT count(*) FROM public.igi_models WHERE state = 'reserved' INTO v_actual;
  IF v_actual <> 15 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'reserved serials', v_actual, 15;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('reserved serials', 34), v_actual;
  SELECT count(*) FROM public.igi_models WHERE state = 'awaiting_serial' INTO v_actual;
  IF v_actual <> 3 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'models awaiting a serial', v_actual, 3;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('models awaiting a serial', 34), v_actual;
  SELECT coalesce(sum(qty), 0) FROM public.igi_batches INTO v_actual;
  IF v_actual <> 62999 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'certificates ordered', v_actual, 62999;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('certificates ordered', 34), v_actual;
  SELECT coalesce(sum(qty_issued), 0) FROM public.igi_visit_lines INTO v_actual;
  IF v_actual <> 3778 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'issued with a model', v_actual, 3778;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('issued with a model', 34), v_actual;
  SELECT coalesce(sum(unattributed_total), 0) FROM public.igi_visits INTO v_actual;
  IF v_actual <> 3245 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'issued with no model', v_actual, 3245;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('issued with no model', 34), v_actual;
  SELECT (SELECT coalesce(sum(qty), 0) FROM public.igi_batches) - (SELECT coalesce(sum(qty_issued), 0) FROM public.igi_visit_lines) INTO v_actual;
  IF v_actual <> 59221 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'unissued at IGI', v_actual, 59221;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('unissued at IGI', 34), v_actual;
  SELECT count(*) FROM public.igi_visits INTO v_actual;
  IF v_actual <> 23 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'movements', v_actual, 23;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('movements', 34), v_actual;
  SELECT count(*) FROM public.igi_visits WHERE date_suspect INTO v_actual;
  IF v_actual <> 4 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'movements with a mistyped date', v_actual, 4;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('movements with a mistyped date', 34), v_actual;
  SELECT count(*) FROM public.igi_descriptions INTO v_actual;
  IF v_actual <> 116 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'descriptions classified', v_actual, 116;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('descriptions classified', 34), v_actual;
  SELECT count(*) FROM public.igi_descriptions WHERE model_id IS NOT NULL INTO v_actual;
  IF v_actual <> 26 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'descriptions linked to a model', v_actual, 26;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('descriptions linked to a model', 34), v_actual;
  SELECT count(*) FROM public.igi_descriptions WHERE kind = 'certificate' AND model_id IS NULL INTO v_actual;
  IF v_actual <> 0 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'descriptions still needing a human', v_actual, 0;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('descriptions still needing a human', 34), v_actual;
  SELECT coalesce(sum(total_pcs), 0) FROM public.igi_shelf_snapshots WHERE model_id IS NOT NULL INTO v_actual;
  IF v_actual <> 3504 THEN
    RAISE EXCEPTION '% is %, expected % — nothing has been saved', 'certificates on the shelf', v_actual, 3504;
  END IF;
  RAISE NOTICE '  ok  % = %', rpad('certificates on the shelf', 34), v_actual;
  RAISE NOTICE '';
  RAISE NOTICE 'IGI: ALL FIGURES MATCH';
END $check$;

COMMIT;
