// Country list for ClientGate searchable dropdown.
// Source: common English short country names (broadly ISO 3166 aligned).

/**
 * Maps non-English country names, common abbreviations, and known typos to
 * their canonical English names. Keys must be lowercase. Add new entries here
 * whenever a new variant surfaces in the database — no migration required.
 */
export const COUNTRY_ALIASES = {
  // Dutch
  duitsland: 'Germany',
  nederland: 'Netherlands',
  nederlanden: 'Netherlands',
  belgie: 'Belgium',
  belgiё: 'Belgium',
  oostenrijk: 'Austria',
  zwitserland: 'Switzerland',
  spanje: 'Spain',
  italie: 'Italy',
  frankrijke: 'France',

  // French
  allemagne: 'Germany',
  'pays-bas': 'Netherlands',
  belgique: 'Belgium',
  autriche: 'Austria',
  suisse: 'Switzerland',
  espagne: 'Spain',
  italie: 'Italy',
  'royaume-uni': 'United Kingdom',

  // Italian / other Romance
  italia: 'Italy',
  germanie: 'Germany',

  // Abbreviations
  uk: 'United Kingdom',
  'u.k.': 'United Kingdom',
  uae: 'United Arab Emirates',
  uea: 'United Arab Emirates',
  'u.a.e.': 'United Arab Emirates',
  usa: 'United States',
  'u.s.a.': 'United States',
  us: 'United States',

  // ISO 3166-1 alpha-2 / alpha-3 that Claude and the team type in chat
  de: 'Germany',
  deu: 'Germany',
  deutschland: 'Germany',
  fr: 'France',
  fra: 'France',
  frankreich: 'France',
  it: 'Italy',
  ita: 'Italy',
  at: 'Austria',
  aut: 'Austria',
  ch: 'Switzerland',
  che: 'Switzerland',
  nl: 'Netherlands',
  nld: 'Netherlands',
  be: 'Belgium',
  bel: 'Belgium',
  es: 'Spain',
  esp: 'Spain',
  pt: 'Portugal',
  prt: 'Portugal',
  lu: 'Luxembourg',
  lux: 'Luxembourg',

  // Cities/regions stored as countries
  dubai: 'United Arab Emirates',
  'abu dhabi': 'United Arab Emirates',
  corse: 'France',       // Corsica is French territory
  corsica: 'France',
  holland: 'Netherlands', // informal; technically only 2 of 12 provinces

  // Native-language country names seen on business cards at fairs. OCR returns
  // the card's own spelling ("Deutschland", "Italia", "Polska"), which used to
  // fall through to English outreach. See languagesForCountry.
  espana: 'Spain',
  'españa': 'Spain',
  polska: 'Poland',
  polen: 'Poland',
  pologne: 'Poland',
  sverige: 'Sweden',
  norge: 'Norway',
  danmark: 'Denmark',
  suomi: 'Finland',
  schweiz: 'Switzerland',
  svizzera: 'Switzerland',
  'österreich': 'Austria',
  oesterreich: 'Austria',
  osterreich: 'Austria',
  'magyarország': 'Hungary',
  magyarorszag: 'Hungary',
  'česko': 'Czech Republic',
  cesko: 'Czech Republic',
  'türkiye': 'Turkey',
  turkiye: 'Turkey',
  'ελλάδα': 'Greece',
  ellada: 'Greece',
  hellas: 'Greece',
  brasil: 'Brazil',
  'méxico': 'Mexico',
  mexiko: 'Mexico',
  portugalia: 'Portugal',
  '日本': 'Japan',
  nippon: 'Japan',
  japon: 'Japan',
  '中国': 'China',
  zhongguo: 'China',
  '대한민국': 'South Korea',
  '한국': 'South Korea',
  korea: 'South Korea',
  'ישראל': 'Israel',
  israel: 'Israel',

  // ISO alpha-2/alpha-3 for the rest of the fair circuit ("DE" and "IT" were
  // already above); some cards print only the code.
  gb: 'United Kingdom',
  gbr: 'United Kingdom',
  ie: 'Ireland',
  irl: 'Ireland',
  pl: 'Poland',
  pol: 'Poland',
  se: 'Sweden',
  dk: 'Denmark',
  no: 'Norway',
  fi: 'Finland',
  gr: 'Greece',
  grc: 'Greece',
  tr: 'Turkey',
  tur: 'Turkey',
  cz: 'Czech Republic',
  hu: 'Hungary',
  ro: 'Romania',
  bg: 'Bulgaria',
  il: 'Israel',
  jp: 'Japan',
  jpn: 'Japan',
  cn: 'China',
  chn: 'China',
  kr: 'South Korea',
  in: 'India',
  ind: 'India',
  ae: 'United Arab Emirates',
  br: 'Brazil',
  mx: 'Mexico',
  ar: 'Argentina',
  au: 'Australia',
  ca: 'Canada',
  can: 'Canada',
  za: 'South Africa',
  hk: 'Hong Kong',
  sg: 'Singapore',
  th: 'Thailand',
  'united states of america': 'United States',

  // Typos
  bulgary: 'Bulgaria',
  bulgarie: 'Bulgaria',
  switzeland: 'Switzerland',
  switserland: 'Switzerland',
  germnay: 'Germany',
  gernamy: 'Germany',
  neitherlands: 'Netherlands',
}

const _countriesLower = null // lazy-initialised below

let _cl = null
function countriesLower() {
  if (!_cl) _cl = COUNTRIES.map(c => c.toLowerCase())
  return _cl
}

/**
 * Normalise a raw country string (from user input or legacy database data) to
 * its canonical English name as found in COUNTRIES.
 *
 * Resolution order:
 *  1. COUNTRY_ALIASES exact match (handles non-English names + typos)
 *  2. Case-insensitive exact match against COUNTRIES
 *  3. Substring match (e.g. "United Kingdom of …" → "United Kingdom")
 *  4. Title-cased fallback
 */
export function normalizeCountry(raw) {
  if (!raw || !String(raw).trim()) return 'Unknown'
  const cleaned = String(raw).trim().replace(/\s+/g, ' ')
  const lower = cleaned.toLowerCase()

  // 1. Alias map (non-English names, abbreviations, typos)
  if (COUNTRY_ALIASES[lower]) return COUNTRY_ALIASES[lower]

  const cl = countriesLower()

  // 2. Exact case-insensitive match
  const idx = cl.indexOf(lower)
  if (idx >= 0) return COUNTRIES[idx]

  // 3. Substring match (e.g. "United Kingdom" inside "United Kingdom of Great Britain")
  for (let i = 0; i < COUNTRIES.length; i++) {
    if (lower.includes(cl[i])) return COUNTRIES[i]
  }

  // 4. Title-case fallback
  return cleaned
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')
}

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]
